### PR TITLE
Initial pass at 1.16 fixes

### PR DESCRIPTION
**Pull request by hyperbolic2346**
Untested fixes for 1.16 changes

https://bugs.launchpad.net/cdk-addons/+bug/1841674

### CODE REVIEW

**Review by tvansteenburgh — COMMENTED** [review]
Please explain why the `selector -> matchLabels -> k8s-app` sections were added.

**Comment by hyperbolic2346** [comment]
@tvansteenburgh One of the changes in the API spec from beta to v1 is that .spec.selector is now a required field. I've had to add that when it was absent from templates.

**Comment by Cynerva** [comment]
@hyperbolic2346 In testing, I found a couple that still needed fixing. I've pushed new commits for those, and confirmed that the charm is now able to successfully apply all templates. Please review.

**Comment by hyperbolic2346** [comment]
Looks good. Sorry I missed those.

**Review by Cynerva — APPROVED** [review]

**Pull request merged**
